CREATE TABLE crawl_checkpoints (
  source_code VARCHAR(64) NOT NULL,
  full_completed TINYINT UNSIGNED NOT NULL DEFAULT 0,
  checkpoint JSON NULL,
  pending_checkpoint JSON NULL,
  current_mode VARCHAR(32) NULL,
  current_status VARCHAR(32) NOT NULL DEFAULT 'idle',
  discovered_count INT UNSIGNED NOT NULL DEFAULT 0,
  imported_count INT UNSIGNED NOT NULL DEFAULT 0,
  duplicate_count INT UNSIGNED NOT NULL DEFAULT 0,
  ignored_count INT UNSIGNED NOT NULL DEFAULT 0,
  failed_count INT UNSIGNED NOT NULL DEFAULT 0,
  lease_owner VARCHAR(128) NULL,
  lease_until DATETIME(3) NULL,
  error_summary VARCHAR(2000) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  last_successful_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (source_code),
  CONSTRAINT chk_crawl_checkpoint_full CHECK (full_completed IN (0, 1)),
  KEY idx_crawl_checkpoint_status(current_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE crawl_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_code VARCHAR(64) NOT NULL,
  source_record_key VARCHAR(512) NOT NULL,
  source_url VARCHAR(2048) NOT NULL,
  source_modified_at DATETIME(3) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  normalized_term VARCHAR(255) NULL,
  candidate_id BIGINT UNSIGNED NULL,
  duplicate_target_type VARCHAR(32) NULL,
  duplicate_target_id BIGINT UNSIGNED NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  next_attempt_at DATETIME(3) NULL,
  lease_owner VARCHAR(128) NULL,
  lease_until DATETIME(3) NULL,
  error_type VARCHAR(64) NULL,
  error_message VARCHAR(2000) NULL,
  processed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT fk_crawl_record_checkpoint FOREIGN KEY (source_code)
    REFERENCES crawl_checkpoints(source_code) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_crawl_record_candidate FOREIGN KEY (candidate_id)
    REFERENCES candidate_entries(id) ON DELETE SET NULL ON UPDATE CASCADE,
  UNIQUE KEY uk_crawl_source_record(source_code, source_record_key),
  KEY idx_crawl_record_claim(source_code, status, next_attempt_at, lease_until),
  KEY idx_crawl_record_candidate(candidate_id),
  KEY idx_crawl_record_processed(processed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
